# The URL the site will be built for
base_url = "https://hexadata-com-ar.github.io"

title = "Hexadata"
author = "Victor Villarreal"
description = "Somos Hexadata, un desarrollo educativo-tecnológico jóven."

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "vonge"

taxonomies = [
    { name = "tags", feed = true},
]

[markdown]

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
logo_image = ""
twitter_handle = "MefhigosetH"

navigation = [
    { url = "$BASE_URL", title = "Inicio" },
    { url = "$BASE_URL/projects", title = "Productos" },
]

social_icons = [
    { url = "https://github.com/hexadata-com-ar", icon = "GitHub" },
    { url = "$BASE_URL/atom.xml", icon = "RSS" },
]

[[extra.content_blocks]]
block = "hero"
title = "Termómetro Edutemp Wi-Fi"
description_html = "Sensor de temperatura inteligente especialmente pensado para el ámbito educativo. Sonda sumergible. No requiere Internet. Permite hasta 8 usuarios conectados. Graficas en tiempo real. Fórmulas físicas en pantalla."
image = "projects/edutemp/ecommerce_up.png"
image_alt = "Primer plano de circuitos integrados en una PCB. Autor: Jakub Pabis"
cta_button_link = "/projects/edutemp/"
cta_button = "+ Info"
works_button_link = "#projects"
works_button = "Mas productos"

[[extra.content_blocks]]
block = "projects-section"
title = "Nuestros productos"
description_html = """
    <p>Una selección de nuestros desarrollos más recientes, soluciones de software e integraciones técnicas diseñadas para resolver problemas reales con código eficiente.</p>"""
link_url = "/projects"
show_projects = true

[extra.footer]
menu = [
    { url = "$BASE_URL", title = "Inicio" },
    { url = "$BASE_URL/projects/", title = "Productos" },
]
